title: Open Aviation Data

description: >- # this means to ignore newlines until "baseurl:"
  A comprehensive collection of open aviation data sources covering air traffic management, 
  flight operations, aircraft performance, airport infrastructure, surveillance systems, 
  and weather information. This repository aims to provide researchers, analysts, and 
  aviation professionals with easy access to essential aviation-related datasets and resources.

domain: open-aviation.github.io
url: "https://open-aviation.github.io"
baseurl: "/atmdata" # the subpath of your site, e.g. /blog

# Build settings
include: ["_pages"]
highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-feed
