title: Open Aviation Data
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: open-aviation.github.io
url: "https://open-aviation.github.io"
baseurl: "/atmdata" # the subpath of your site, e.g. /blog

# Build settings
include: ["_pages"]
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions:
    ["footnotes", "tables", "no_intra_emphasis", "autolink", "xhtml", "smart"]
plugins:
  - jekyll-feed
